/*
Copyright © 2026
*/
package cmd

import (
	"github.com/padiazg/pantry/internal/config"
	"github.com/padiazg/pantry/pkg/logger"
	"github.com/spf13/cobra"
)

var (
	cfgFile string
	cfg     *config.Config
)

// rootCmd represents the base command when called without any subcommands
var rootCmd = &cobra.Command{
	Use:   "pantry",
	Short: "pantry - Built with hexagonal architecture",
	Long: `pantry application generated by HexaGo.

This application follows Hexagonal Architecture (Ports & Adapters) pattern,
ensuring proper separation of concerns and maintainability.

Architecture layers:
  - Core Domain: Pure business logic and entities
  - services: Application business logic orchestration
  - Adapters: External interfaces (HTTP, database, etc.)
  - Infrastructure: Cross-cutting concerns (config, logging, etc.)`,
}

// Execute adds all child commands to the root command and sets flags appropriately.
// This is called by main.main(). It only needs to happen once to the rootCmd.
func Execute() error {
	return rootCmd.Execute()
}

func init() {
	cobra.OnInitialize(initConfig)

	// Persistent flags
	rootCmd.PersistentFlags().StringVar(&cfgFile, "config", "", "config file (default is .pantry.yaml)")
}

// initConfig reads in config file and ENV variables if set.
func initConfig() {
	var err error
	cfg, err = config.Load(cfgFile)
	if err != nil {
		logger.Fatal("Failed to load configuration: %v", err)
	}
}

// GetConfig returns the global configuration
func GetConfig() *config.Config {
	return cfg
}
