name: crap
on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  threshold:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.26.2'
          cache: true
      - name: install go-crap
        run: go install github.com/padiazg/go-crap@latest
      - name: score
        run: go-crap scan --fail-above --threshold 30 --exclude '.*_test\.go'

  pr-comment:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.26.2'
          cache: true

      - name: install gremlins
        run: go install github.com/go-gremlins/gremlins/cmd/gremlins@latest
      
      - name: mutation testing
        run: gremlins unleash --output=mutation-report.json          

      - name: install go-crap
        run: go install github.com/padiazg/go-crap@latest

      - name: generate pr comment
        run: go-crap scan --format pr-comment --threshold 30 --exclude '.*_test\.go' --output pr-comment.md  --mutation-report mutation-report.json || true

      - name: get pr number
        run: echo "${{ github.event.pull_request.number }}" > pr-number.txt

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: crap-comment
          path: |
            pr-comment.md
            pr-number.txt
          if-no-files-found: ignore
